### ISSUE TITLE
其实可以不用这么麻烦的

### ISSUE THREAD

**Issue by Heisenberglue** [q4w5e6/ECUT-Auto-Login#2]
在路由器管理界面-->上网设置-->选择PPPoE方式,并且填写校园网账号密码,账号栏需要加后缀,同你文档里写的一样:

> 电信是telecom，移动是cmcc，联通是unicom
  填写完成后让路由器正常拨号就行了.

**Comment by q4w5e6** [comment]
是吗，下个学期我看看

**Comment by q4w5e6** [comment]
好的，可以了，谢谢你
